### ISSUE TITLE
javax.net.ssl.SSLHandshakeException issue with DQLTesterFX, openjdk12, Documentum 16.4

### ISSUE THREAD

**Issue by SreecharanShroff** [HetBenkt/DQL-Tester-FX#18]
C:\Builds\DQLTesterFX>"C:\Builds\jdk-12.0.2\bin\java.exe" --module-path %PATH_TO_FX% --add-modules=javafx.controls,javafx.fxml -cp DQLTesterFX.jar;lib\*;config nl.bos.Main
Nov 02, 2019 12:11:11 PM nl.bos.MyApplication tryDevModeConnection
INFO: Login with connect button
12:11:13,052 ERROR [pool-2-thread-1] com.documentum.fc.common.DfPreferences - [DFC_PREFERENCE_BAD_VALUE] Bad value for preference "dfc.date_format", value="M/d/yyyy, h:mm:ss a"
com.documentum.fc.common.DfException: Illegal syntax found in the date format 'M/d/yyyy, h:mm:ss a'. The default localized short date format will be used.
        at com.documentum.fc.common.DfException.newIllegalDateFormatException(DfException.java:109)
        at com.documentum.fc.common.DfPreferences$DateFormatHandler.set(DfPreferences.java:1959)
        at com.documentum.fc.client.DfTypedObject.doSetString(DfTypedObject.java:1441)
        at com.documentum.fc.client.DfTypedObject.setString(DfTypedObject.java:1418)
        at com.documentum.fc.common.impl.preferences.TypedPreferences.loadProperty(TypedPreferences.java:465)
        at com.documentum.fc.common.impl.preferences.TypedPreferences.loadProperties(TypedPreferences.java:343)
        at com.documentum.fc.common.DfPreferences.loadProperties(DfPreferences.java:377)
        at com.documentum.fc.common.impl.preferences.PreferencesManager.<init>(PreferencesManager.java:38)
        at com.documentum.fc.common.DfPreferences.initialize(DfPreferences.java:64)
        at com.documentum.fc.common.DfPreferences.getInstance(DfPreferences.java:43)
        at com.documentum.fc.client.DfSimpleDbor.getDefaultDbor(DfSimpleDbor.java:78)
        at com.documentum.fc.client.DfSimpleDbor.<init>(DfSimpleDbor.java:66)
        at com.documentum.fc.client.DfClient$ClientImpl.<init>(DfClient.java:350)
        at com.documentum.fc.client.DfClient.<clinit>(DfClient.java:766)
        at com.documentum.com.DfClientX.getLocalClient(DfClientX.java:43)
        at nl.bos.Repository.obtainRepositoryMap(Repository.java:87)
        at nl.bos.InitRepositoryList.call(InitRepositoryList.java:15)
        at nl.bos.InitRepositoryList.call(InitRepositoryList.java:9)
        at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
12:11:13,614 ERROR [pool-2-thread-1] com.documentum.fc.common.DfPreferences - [DFC_PREFERENCE_BAD_VALUE] Bad value for preference "dfc.date_format", value="M/d/yyyy, h:mm:ss a"
com.documentum.fc.common.DfException: Illegal syntax found in the date format 'M/d/yyyy, h:mm:ss a'. The default localized short date format will be used.
        at com.documentum.fc.common.DfException.newIllegalDateFormatException(DfException.java:109)
        at com.documentum.fc.common.DfPreferences$DateFormatHandler.set(DfPreferences.java:1959)
        at com.documentum.fc.client.DfTypedObject.doSetString(DfTypedObject.java:1441)
        at com.documentum.fc.client.DfTypedObject.setString(DfTypedObject.java:1418)
        at com.documentum.fc.common.impl.preferences.TypedPreferences.loadProperty(TypedPreferences.java:465)
        at com.documentum.fc.common.impl.preferences.TypedPreferences.loadProperties(TypedPreferences.java:343)
        at com.documentum.fc.common.DfPreferences.loadProperties(DfPreferences.java:377)
        at com.documentum.fc.common.impl.preferences.PreferencesManager.<init>(PreferencesManager.java:39)
        at com.documentum.fc.common.DfPreferences.initialize(DfPreferences.java:64)
        at com.documentum.fc.common.DfPreferences.getInstance(DfPreferences.java:43)
        at com.documentum.fc.client.DfSimpleDbor.getDefaultDbor(DfSimpleDbor.java:78)
        at com.documentum.fc.client.DfSimpleDbor.<init>(DfSimpleDbor.java:66)
        at com.documentum.fc.client.DfClient$ClientImpl.<init>(DfClient.java:350)
        at com.documentum.fc.client.DfClient.<clinit>(DfClient.java:766)
        at com.documentum.com.DfClientX.getLocalClient(DfClientX.java:43)
        at nl.bos.Repository.obtainRepositoryMap(Repository.java:87)
        at nl.bos.InitRepositoryList.call(InitRepositoryList.java:15)
        at nl.bos.InitRepositoryList.call(InitRepositoryList.java:9)
        at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
Nov 02, 2019 12:11:18 PM nl.bos.Repository obtainRepositoryMap
SEVERE: Request to Docbroker "OPENTEXT16X:1489" failed
com.documentum.fc.client.DfDocbrokerException: Request to Docbroker "OPENTEXT16X:1489" failed
        at com.documentum.fc.client.DfDocbrokerException.newRequestFailedException(DfDocbrokerException.java:12)
        at com.documentum.fc.client.impl.docbroker.DocbaseMapBuilder.getMap(DocbaseMapBuilder.java:42)
        at com.documentum.fc.client.impl.docbroker.DocbrokerClient.getDocbaseMap(DocbrokerClient.java:176)
        at com.documentum.fc.client.DfClient$ClientImpl.getDocbaseMap(DfClient.java:415)
        at nl.bos.Repository.obtainRepositoryMap(Repository.java:90)
        at nl.bos.InitRepositoryList.call(InitRepositoryList.java:15)
        at nl.bos.InitRepositoryList.call(InitRepositoryList.java:9)
        at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: com.documentum.fc.client.DfIOException: Server communication failure
        at com.documentum.fc.client.DfIOException.newCommunicationFailureException(DfIOException.java:16)
        at com.documentum.fc.client.impl.connection.netwise.AbstractNetwiseRpcClient.sendMessage(AbstractNetwiseRpcClient.java:216)
        at com.documentum.fc.client.impl.connection.docbroker.netwise.NetwiseDocbrokerRpcClient.requestObject(NetwiseDocbrokerRpcClient.java:58)
        at com.documentum.fc.client.impl.connection.docbroker.DocbrokerConnection.requestObject(DocbrokerConnection.java:80)
        at com.documentum.fc.client.impl.docbroker.MapBuilder.issueRequest(MapBuilder.java:34)
        at com.documentum.fc.client.impl.docbroker.DocbaseMapBuilder.getDataFromDocbroker(DocbaseMapBuilder.java:63)
        at com.documentum.fc.client.impl.docbroker.DocbaseMapBuilder.getMap(DocbaseMapBuilder.java:32)
        ... 10 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:307)
        at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:285)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:180)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1180)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1091)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:721)
        at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:998)
        at com.documentum.fc.impl.util.io.MessageChannel.writeSocket(MessageChannel.java:261)
        at com.documentum.fc.impl.util.io.MessageChannel.write(MessageChannel.java:219)
        at com.documentum.fc.client.impl.connection.netwise.AbstractNetwiseRpcClient.sendMessage(AbstractNetwiseRpcClient.java:211)
        ... 15 more

Nov 02, 2019 12:11:19 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Caught 'java.lang.ClassCastException: class java.lang.String cannot be cast to class javafx.scene.paint.Paint (java.lang.String is in module java.base of loader 'bootstrap'; javafx.scene.paint.Paint is in module javafx.graphics of loader 'app')' while converting value for '-fx-background-color' from rule '*.code-area:focused' in stylesheet jar:file:/C:/Builds/DQLTesterFX/DQLTesterFX.jar!/nl/bos/themes/dql-keywords.css

![image](https://user-images.githubusercontent.com/13052236/68075206-b269a580-fdca-11e9-9de2-4ea942ed2abb.png)

**Comment by SreecharanShroff** [comment]
works fine after updating dfc.properties as per the readme
